obj-y += board.o
obj-y += flash-header-kosagi-novena-6dl.dcd.o flash-header-kosagi-novena-6q.dcd.o
extra-y += flash-header-kosagi-novena-6dl.dcd.S flash-header-kosagi-novena-6q.dcd.S
extra-y += flash-header-kosagi-novena-6dl.dcd flash-header-kosagi-novena-6q.dcd
lwl-y += lowlevel.o
